/**
 * Story 2.4 — parsing an OID4VP authorization request.
 *
 * This is the untrusted-input boundary for the entire presentation flow. What
 * happens after this function returns `ok` is: a consent screen names a party,
 * the user approves, and credential material is POSTed to an endpoint. Every
 * one of those three is attacker-influenced unless this function constrains it.
 *
 * PARSES, never casts (FR16c). Unknown parameters are dropped rather than
 * carried, so nothing downstream can start trusting a field a verifier invented.
 *
 * ── The control that matters most: response_uri binding ────────────────────
 *
 * Under `direct_post` the wallet POSTs the `vp_token` to `response_uri`. If that
 * URI is not bound to the party the consent screen NAMED, then the screen says
 * "share with verifier.example.org" and the credential goes to
 * attacker.example. The user's decision and the actual effect come apart, which
 * makes consent theatre.
 *
 * Binding is an EXACT authority match against the client_id's host — not a
 * prefix, not a suffix, not `endsWith`. `evil.verifier.example.org` and
 * `verifier.example.org.attacker.example` both survive a sloppy comparison, and
 * `https://verifier.example.org@attacker.example/` has authority
 * `attacker.example` while reading as the verifier to a human.
 *
 * ── What this does NOT do ──────────────────────────────────────────────────
 *
 * It does not authenticate the verifier. `client_id_scheme: did` says the
 * verifier CLAIMS a DID; proving it requires verifying a signed request object
 * against that DID's document, which needs the Story 2.1 resolver and is the
 * next slice. Until then a consent screen must present the client_id as a
 * claim, not as an established identity — see `verified` on the returned shape,
 * which is deliberately always `false` here so a UI cannot read this parser's
 * success as authentication.
 */
import {
  isSupportedResponseMode,
  isSupportedClientIdScheme,
  CLIENT_ID_AUTHORITY_KIND,
  type SupportedResponseMode,
  type SupportedClientIdScheme,
} from './profile'
import { parseDid } from '@/background/did/did-syntax'
import { buildDidWebUrl } from '@/background/did/did-web-url'

export type AuthorizationRequestReason =
  | 'not-an-object'
  | 'unsupported-response-type'
  | 'unsupported-response-mode'
  | 'unsupported-client-id-scheme'
  | 'client-id-scheme-mismatch'
  | 'missing-response-uri'
  | 'invalid-response-uri'
  | 'response-uri-not-bound-to-client'
  | 'missing-nonce'
  | 'weak-nonce'
  | 'no-requested-claims'
  | 'too-many-requested-claims'

export interface AuthorizationRequest {
  clientId: string
  clientIdScheme: SupportedClientIdScheme
  responseMode: SupportedResponseMode
  /** Where the vp_token goes. Guaranteed https and bound to `clientId`. */
  responseUri: string
  nonce: string
  state: string | null
  /** Deduplicated JSONPath claim references, in first-seen order. */
  requestedClaims: readonly string[]
  /**
   * Whether the VERIFIER has been authenticated. Always `false` from this
   * parser — see the header. Present so a consent UI must handle the
   * distinction explicitly rather than infer trust from a successful parse.
   */
  verified: false
}

export type ParseAuthorizationRequestResult =
  | { ok: true; value: AuthorizationRequest }
  | { ok: false; reason: AuthorizationRequestReason }

/** A consent screen listing hundreds of claims cannot be read by a human. */
export const MAX_REQUESTED_CLAIMS = 32

/**
 * A nonce shorter than this is guessable, and the nonce is the only replay
 * defence in this flow: a presentation built against a predictable nonce can be
 * replayed at any verifier that accepts it.
 *
 * ⚠️ NARROWING, flagged because it has an interop cost. OpenID4VP states no
 * normative minimum, and the nonce in the OIDC spec's own EXAMPLES
 * (`n-0S6_WzA2Mj`) is 12 characters — so this refuses requests that some real
 * verifiers will send, and the wallet will look broken to them rather than
 * insecure. 16 base64url characters is roughly 96 bits.
 *
 * The tradeoff: the nonce is generated by the VERIFIER, so a weak one is
 * primarily their exposure, not ours — which argues for accepting it and
 * letting them carry the risk. Against that, we are the party whose credential
 * gets replayed. Erring strict is the reversible choice; lower it here if
 * conformance testing (Story 2.5) shows real verifiers failing on it.
 */
export const MIN_NONCE_LENGTH = 16

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function readString(source: Record<string, unknown>, key: string): string | null {
  const raw = source[key]
  return typeof raw === 'string' ? raw : null
}

/**
 * The authority a client_id speaks for, or null when it names none.
 *
 * `did:web` maps to its host via the SAME builder the resolver uses — so the
 * host this binding is checked against is exactly the host a resolution would
 * contact, and the SSRF/reserved-zone rules apply here too rather than being
 * re-derived (and drifting).
 */
function clientAuthority(scheme: SupportedClientIdScheme, clientId: string): string | null {
  // Branch on the KIND, not the scheme NAME — the names live in `profile.ts`
  // and this module must not become a second source of them.
  if (CLIENT_ID_AUTHORITY_KIND[scheme] === 'dns') {
    // The client_id IS the DNS name asserted in the certificate's SAN. Reuse
    // the resolver's host rules so an SSRF-shaped or reserved-zone client_id is
    // refused here too, rather than re-derived and drifting.
    const built = buildDidWebUrl(clientId)
    return built.ok ? new URL(built.value).host : null
  }

  const parsed = parseDid(clientId)
  if (!parsed.ok) return null
  // Only did:web names a network authority a response_uri can be bound to.
  if (parsed.value.method !== 'web') return null
  const built = buildDidWebUrl(parsed.value.methodSpecificId)
  return built.ok ? new URL(built.value).host : null
}

export function parseAuthorizationRequest(value: unknown): ParseAuthorizationRequestResult {
  if (!isRecord(value)) return { ok: false, reason: 'not-an-object' }

  if (readString(value, 'response_type') !== 'vp_token') {
    return { ok: false, reason: 'unsupported-response-type' }
  }

  const responseMode = value.response_mode
  if (!isSupportedResponseMode(responseMode)) {
    return { ok: false, reason: 'unsupported-response-mode' }
  }

  const clientIdScheme = value.client_id_scheme
  if (!isSupportedClientIdScheme(clientIdScheme)) {
    return { ok: false, reason: 'unsupported-client-id-scheme' }
  }

  const clientId = readString(value, 'client_id')
  if (clientId === null || clientId.length === 0) {
    return { ok: false, reason: 'client-id-scheme-mismatch' }
  }

  const authority = clientAuthority(clientIdScheme, clientId)
  if (authority === null) return { ok: false, reason: 'client-id-scheme-mismatch' }

  // ── response_uri, and its binding to the client ──────────────────────────
  const rawResponseUri = readString(value, 'response_uri')
  if (rawResponseUri === null || rawResponseUri.length === 0) {
    return { ok: false, reason: 'missing-response-uri' }
  }

  let responseUrl: URL
  try {
    responseUrl = new URL(rawResponseUri)
  } catch {
    return { ok: false, reason: 'invalid-response-uri' }
  }
  if (responseUrl.protocol !== 'https:') return { ok: false, reason: 'invalid-response-uri' }

  // 🔒 EXACT authority match. `URL.host` already excludes userinfo, so
  // `https://verifier.example.org@attacker.example/` compares as
  // `attacker.example` and is refused — which is the point, because it reads as
  // the verifier to a human skimming a consent screen.
  if (responseUrl.host !== authority) {
    return { ok: false, reason: 'response-uri-not-bound-to-client' }
  }

  // ── nonce ────────────────────────────────────────────────────────────────
  const nonce = readString(value, 'nonce')
  if (nonce === null || nonce.trim().length === 0) return { ok: false, reason: 'missing-nonce' }
  if (nonce.length < MIN_NONCE_LENGTH) return { ok: false, reason: 'weak-nonce' }

  // ── requested claims ─────────────────────────────────────────────────────
  const claims = collectRequestedClaims(value.presentation_definition)
  if (claims === 'too-many') return { ok: false, reason: 'too-many-requested-claims' }
  if (claims.length === 0) return { ok: false, reason: 'no-requested-claims' }

  return {
    ok: true,
    value: {
      clientId,
      clientIdScheme,
      responseMode,
      responseUri: responseUrl.toString(),
      nonce,
      state: readString(value, 'state'),
      requestedClaims: claims,
      verified: false,
    },
  }
}

/**
 * Pull the claim paths out of a DIF Presentation Definition.
 *
 * Malformed entries are SKIPPED rather than failing the request: a verifier
 * sending one bad field descriptor among good ones is a bug at their end, and
 * refusing the whole exchange helps nobody. The claims that survive are the
 * ones the consent screen will list, so skipping is safe in the direction that
 * matters — we can only ever ask for LESS than was requested, never more.
 */
function collectRequestedClaims(definition: unknown): readonly string[] | 'too-many' {
  if (!isRecord(definition)) return []
  const descriptors = definition.input_descriptors
  if (!Array.isArray(descriptors)) return []

  const seen = new Set<string>()
  const out: string[] = []

  for (const descriptor of descriptors) {
    if (!isRecord(descriptor)) continue
    const constraints = descriptor.constraints
    if (!isRecord(constraints)) continue
    const fields = constraints.fields
    if (!Array.isArray(fields)) continue

    for (const field of fields) {
      if (!isRecord(field)) continue
      const paths = field.path
      if (!Array.isArray(paths)) continue
      for (const path of paths) {
        if (typeof path !== 'string' || path.length === 0) continue
        if (seen.has(path)) continue
        seen.add(path)
        out.push(path)
        if (out.length > MAX_REQUESTED_CLAIMS) return 'too-many'
      }
    }
  }

  return out
}
